### PR TITLE
MNW-97 update swap page UI

### PR DESCRIPTION
**Pull request by NotEternal**
Task: https://mnw.atlassian.net/browse/MNW-153

Builds:
- mainnet: https://deploy-preview-50--preview-mainnet-mynearwallet.netlify.app/
- testnet: https://deploy-preview-50--preview-testnet-mynearwallet.netlify.app/

## Changes:
- remove legacy swap
- move all swap-related components to `pages/TokenSwap/...` and do some refactor
- update swap details components and display it in the swap and preview screens
- check if the user has enough balance for input and for fee

## Demo:
https://www.loom.com/share/cbe4bc76244149cca3e81f61ef6d72a8

## Preview:
result

### If not enough for fee
forFee

### If not enough for fee and for input
forAll

### CODE REVIEW

**Review by loosefer — APPROVED** [review]

**Review by PinkiNice — APPROVED** [review]

**Comment by PinkiNice** [comment]
изображение
Tooltip is being cropped, probably because of "overflow: hidden" ?

**Comment by PinkiNice** [comment]
изображение
Trying to exchange some AURORA => NEAR but getting this error about not enough balance.

Testing account balance:
NEAR 0.00511
AURORA 0.02

**Comment by PinkiNice** [comment]
изображение
NEAR token is not placed first in balances, I guess a mistake?

**Comment by NotEternal** [comment]
> изображение
> 
> Trying to exchange some AURORA => NEAR but getting this error about not enough balance.
> Testing account balance: NEAR 0.00511 AURORA 0.02

I added an additional balance check. It should be fine now.

**Review by PinkiNice — APPROVED** [review]

**Pull request merged**
